name 'spantree-td-agent'
version '0.0.1'
source 'git:Spantree/puppet-module-tdagent.git'
author 'Spantree'
description 'TD Agent for Ubuntu'
summary 'TD Agent for Ubuntu'
license 'ASL 2.0'
project_page 'https://github.com/Spantree/puppet-module-tdagent'

dependency 'puppetlabs/apt', '>=1.1.0 <2.0.0'